### ISSUE TITLE
SafeMath tests not passing

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit-contracts#33]
I'm using testrpc v6.0.3,
Running truffle test and getting these error messages:

  1) Contract: SafeMath should throw an error on addition overflow:
     AssertionError: Invalid opcode error must be returned: expected -1 to be above -1
      at Function.assert.isAbove (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:216091:35)
      at module.exports (test/helpers/assertJump.js:4:10)
      at Context.<anonymous> (test/math/SafeMath.js:58:7)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) Contract: SafeMath should throw an error on multiplication overflow:
     AssertionError: Invalid opcode error must be returned: expected -1 to be above -1
      at Function.assert.isAbove (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:216091:35)
      at module.exports (test/helpers/assertJump.js:4:10)
      at Context.<anonymous> (test/math/SafeMath.js:69:7)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Shrugs** [comment]
That's a lil weird. Any ideas? I assume we're using OZ 1.4.0 SafeMath?
